/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.Conductor.vali;
import Logica.Bascula.bascula;
import Logica.Bascula.busquedasTiquete;
import Logica.Bascula.tiqueteVarios;
import Logica.Laboratorio.laboratorioTiqueteInicial;
import Negocio.Conexion;
import java.sql.ResultSet;
import java.sql.Statement;
import Interfaces.LaboratorioTiqueteInicial;
import Logica.Extras.validaciones;
import Logica.Extras.extras;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Interfaces.Liquidacion;
import static Interfaces.TiqueteVarios.Bas;

/**
 *
 * @author Andre
 */
public class BusquedasTiquete extends javax.swing.JDialog {

    public static LaboratorioTiqueteInicial Lab;
    public static busquedasTiquete busTiquete;
    public static BusquedasTiquete BusTiquete;
    public static bascula bascula;
    public static String claseTiquete, conductor, agricultor;
    public static TiqueteVarios TiqVarios;
    public static tiqueteVarios tiqVarios;
    public static validaciones val, vali;
    public static String consecutivo;
    public static LaboratorioTiqueteInicial TiqLab;
    public static laboratorioTiqueteInicial tiqLab;
    public static Statement st;
    public static Conexion Con;
    public static ResultSet rsconsecutivo;
    public static extras ext;
    public static Liquidacion Liqui;
    private String tiquete;

    /**
     * Creates new form BusquedasTiquete
     */
    public BusquedasTiquete(java.awt.Frame parent, boolean modal,String tiquete) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        claseTiquete = tiquete;
        System.out.println(claseTiquete);
        busTiquete = new busquedasTiquete(claseTiquete);
        ext = new extras();
        vali = new validaciones();
        vali.IDENTIFICACION(txtBCedulaVehiculo);
        vali.NOMBRES(txtBApellidosAgricultor);
        vali.NOMBRES(txtBCiudadAgricultor);
        vali.IDENTIFICACION(txtBCedulaConductor);
        vali.NOMBRES(txtBApellidosConductor);
        vali.NOMBRES(txtBCiudadConductor);
        vali.NOMBRES(txtBMarcaVehiculo);

    }

    private BusquedasTiquete(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel = new javax.swing.JTabbedPane();
        panelAgricultor = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        chCedulaAgricultor = new javax.swing.JCheckBox();
        chApellidosAgricultor = new javax.swing.JCheckBox();
        chCiudadAgricultor = new javax.swing.JCheckBox();
        txtBCedulaVehiculo = new javax.swing.JTextField();
        txtBApellidosAgricultor = new javax.swing.JTextField();
        txtBCiudadAgricultor = new javax.swing.JTextField();
        btnBuscarAgricultor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRefrescarAgricultor = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnGuardarAgricultor = new javax.swing.JButton();
        panelConductor = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        chCedulaConductor = new javax.swing.JCheckBox();
        chApellidosConductor = new javax.swing.JCheckBox();
        chCiudadConductor = new javax.swing.JCheckBox();
        txtBCedulaConductor = new javax.swing.JTextField();
        txtBApellidosConductor = new javax.swing.JTextField();
        txtBCiudadConductor = new javax.swing.JTextField();
        btnBuscarConductor = new javax.swing.JButton();
        btnRefrescarConductor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnGuardarConductor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelVehiculo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        chPlacaVehiculo = new javax.swing.JCheckBox();
        chModeloVehiculo = new javax.swing.JCheckBox();
        chMarcaVehiculo = new javax.swing.JCheckBox();
        txtBPlacaVehiculo = new javax.swing.JTextField();
        txtBModeloVehiculo = new javax.swing.JTextField();
        txtBMarcaVehiculo = new javax.swing.JTextField();
        btnBuscarVehiculo = new javax.swing.JButton();
        btnRefrescarVehiculo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnGuardarVehiculo = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        panelAgricultor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAgricultor.setPreferredSize(new java.awt.Dimension(1007, 367));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chCedulaAgricultor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chCedulaAgricultor.setText("Cedula");
        chCedulaAgricultor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCedulaAgricultorItemStateChanged(evt);
            }
        });

        chApellidosAgricultor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chApellidosAgricultor.setText("Apellidos");
        chApellidosAgricultor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chApellidosAgricultorItemStateChanged(evt);
            }
        });

        chCiudadAgricultor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chCiudadAgricultor.setText("Ciudad");
        chCiudadAgricultor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCiudadAgricultorItemStateChanged(evt);
            }
        });

        txtBCedulaVehiculo.setEditable(false);

        txtBApellidosAgricultor.setEditable(false);

        txtBCiudadAgricultor.setEditable(false);

        btnBuscarAgricultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        btnBuscarAgricultor.setText("Buscar");
        btnBuscarAgricultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAgricultorActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Busquedas:");

        btnRefrescarAgricultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar.png"))); // NOI18N
        btnRefrescarAgricultor.setText("Refrescar");
        btnRefrescarAgricultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarAgricultorActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chCedulaAgricultor)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtBCedulaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chApellidosAgricultor)
                                    .addComponent(txtBApellidosAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBCiudadAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chCiudadAgricultor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefrescarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel16))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chCiudadAgricultor)
                            .addComponent(chApellidosAgricultor)
                            .addComponent(chCedulaAgricultor))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBCiudadAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBApellidosAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBCedulaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefrescarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );

        chCedulaAgricultor.getAccessibleContext().setAccessibleName("chCedulaAgricultor");
        chApellidosAgricultor.getAccessibleContext().setAccessibleName("chApellidosAgricultor");
        txtBCedulaVehiculo.getAccessibleContext().setAccessibleName("txtBCedulaAgricultor");
        txtBApellidosAgricultor.getAccessibleContext().setAccessibleName("txtBApellidosAgricultor");
        txtBCiudadAgricultor.getAccessibleContext().setAccessibleName("txtBCiudadAgricultor");
        btnBuscarAgricultor.getAccessibleContext().setAccessibleName("btnBuscarAgricultor");
        btnRefrescarAgricultor.getAccessibleContext().setAccessibleName("btnRefrescarAgricultor");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("*Seleccione el agricultor en el listado y será visualizado en el tiquete de entrada.");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agricultorx64.png"))); // NOI18N
        jLabel13.setText("AGRICULTOR");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        btnGuardarAgricultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        btnGuardarAgricultor.setText("Guardar");
        btnGuardarAgricultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAgricultorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgricultorLayout = new javax.swing.GroupLayout(panelAgricultor);
        panelAgricultor.setLayout(panelAgricultorLayout);
        panelAgricultorLayout.setHorizontalGroup(
            panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgricultorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgricultorLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        panelAgricultorLayout.setVerticalGroup(
            panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgricultorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel5.getAccessibleContext().setAccessibleName("chApelliidosAgricultor");

        panel.addTab("Agricultor", panelAgricultor);
        panelAgricultor.getAccessibleContext().setAccessibleName("panelAgricultor");

        panelConductor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chCedulaConductor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chCedulaConductor.setText("Cedula");
        chCedulaConductor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCedulaConductorItemStateChanged(evt);
            }
        });

        chApellidosConductor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chApellidosConductor.setText("Apellidos");
        chApellidosConductor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chApellidosConductorItemStateChanged(evt);
            }
        });

        chCiudadConductor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chCiudadConductor.setText("Ciudad");
        chCiudadConductor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCiudadConductorItemStateChanged(evt);
            }
        });

        txtBCedulaConductor.setEditable(false);

        txtBApellidosConductor.setEditable(false);

        txtBCiudadConductor.setEditable(false);

        btnBuscarConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        btnBuscarConductor.setText("Buscar");
        btnBuscarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConductorActionPerformed(evt);
            }
        });

        btnRefrescarConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar.png"))); // NOI18N
        btnRefrescarConductor.setText("Refrescar");
        btnRefrescarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarConductorActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Busquedas:");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBCedulaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chCedulaConductor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chApellidosConductor)
                            .addComponent(txtBApellidosConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBCiudadConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chCiudadConductor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnRefrescarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chCedulaConductor)
                            .addComponent(chApellidosConductor)
                            .addComponent(chCiudadConductor))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBCedulaConductor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBCiudadConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBApellidosConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefrescarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        chCedulaConductor.getAccessibleContext().setAccessibleName("chCedula");
        chApellidosConductor.getAccessibleContext().setAccessibleName("chApelliidos");
        chCiudadConductor.getAccessibleContext().setAccessibleName("chCiudad");
        txtBCedulaConductor.getAccessibleContext().setAccessibleName("txtBCedula");
        txtBApellidosConductor.getAccessibleContext().setAccessibleName("txtBApellidos");
        txtBCiudadConductor.getAccessibleContext().setAccessibleName("txtBCiudad");
        btnBuscarConductor.getAccessibleContext().setAccessibleName("btnBuscar");
        btnRefrescarConductor.getAccessibleContext().setAccessibleName("btnRefrescarConductor");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("*Seleccione el conductor en el listado y será visualizado en el tiquete de entrada.");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(683, 74));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/conductorx64.png"))); // NOI18N
        jLabel14.setText("CONDUCTOR");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        btnGuardarConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        btnGuardarConductor.setText("Guardar");
        btnGuardarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConductorLayout = new javax.swing.GroupLayout(panelConductor);
        panelConductor.setLayout(panelConductorLayout);
        panelConductorLayout.setHorizontalGroup(
            panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConductorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConductorLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        panelConductorLayout.setVerticalGroup(
            panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConductorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        panel.addTab("Conductor", panelConductor);
        panelConductor.getAccessibleContext().setAccessibleName("panelConductor");

        panelVehiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chPlacaVehiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chPlacaVehiculo.setText("Placa");
        chPlacaVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chPlacaVehiculoItemStateChanged(evt);
            }
        });

        chModeloVehiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chModeloVehiculo.setText("Modelo");
        chModeloVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chModeloVehiculoItemStateChanged(evt);
            }
        });

        chMarcaVehiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chMarcaVehiculo.setText("Marca");
        chMarcaVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chMarcaVehiculoItemStateChanged(evt);
            }
        });

        txtBPlacaVehiculo.setEditable(false);

        txtBModeloVehiculo.setEditable(false);

        txtBMarcaVehiculo.setEditable(false);

        btnBuscarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        btnBuscarVehiculo.setText("Buscar");
        btnBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVehiculoActionPerformed(evt);
            }
        });

        btnRefrescarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar.png"))); // NOI18N
        btnRefrescarVehiculo.setText("Refrescar");
        btnRefrescarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarVehiculoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Busquedas:");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chPlacaVehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chModeloVehiculo)
                            .addComponent(txtBModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBMarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chMarcaVehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnRefrescarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chPlacaVehiculo)
                            .addComponent(chModeloVehiculo)
                            .addComponent(chMarcaVehiculo))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBPlacaVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBMarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefrescarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("*Seleccione el vehíulo en el listado y será visualizado en el tiquete de entrada.");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(683, 74));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/vehiculo2.png"))); // NOI18N
        jLabel15.setText("VEHÍCULO");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        btnGuardarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        btnGuardarVehiculo.setText("Guardar");
        btnGuardarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVehiculoLayout = new javax.swing.GroupLayout(panelVehiculo);
        panelVehiculo.setLayout(panelVehiculoLayout);
        panelVehiculoLayout.setHorizontalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelVehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        panelVehiculoLayout.setVerticalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel.addTab("Vehículo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        setBounds(0, 0, 731, 539);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        busTiquete.cerrar(claseTiquete);
        busTiquete.desactivar_checkboxConductor();
        busTiquete.desactivar_checkboxAgricultor();
    }//GEN-LAST:event_formWindowClosing

    private void btnGuardarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConductorActionPerformed
        int rec2 = jTable2.getSelectedRow();
        if (rec2 == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
        } else {
            switch (claseTiquete) {
                case "TiqPrincipal":
                    String placaTiqPrincipal = Bas.txtPlaca.getText();
                    if (!placaTiqPrincipal.equals("")) {
                        int valor = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios realizados?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (valor == JOptionPane.YES_OPTION) {
                            Bas.txtConductor.setText((jTable2.getValueAt(rec2, 1).toString()) + (" " + jTable2.getValueAt(rec2, 2).toString()));
                        } else {
                            JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
                        }
                    } else {
                        Bas.txtConductor.setText((jTable2.getValueAt(rec2, 1).toString()) + (" " + jTable2.getValueAt(rec2, 2).toString()));
                    }
                    conductor = ext.getIdPersonalExterno((jTable2.getValueAt(rec2, 0).toString()), "conductor");
                    bascula.idConductor = conductor;
                    busTiquete.cerrar(claseTiquete);
                    dispose();
                    break;

                case "TiqVarios":
                    String placaTiqVarios = TiqVarios.txtPlaca.getText();
                    if (!placaTiqVarios.equals("")) {
                        int valor = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios realizados?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (valor == JOptionPane.YES_OPTION) {
                            TiqVarios.txtConductor.setText((jTable2.getValueAt(rec2, 1).toString()) + (" " + jTable2.getValueAt(rec2, 2).toString()));
                        } else {
                            JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
                        }
                    } else {
                        TiqVarios.txtConductor.setText((jTable2.getValueAt(rec2, 1).toString()) + (" " + jTable2.getValueAt(rec2, 2).toString()));
                    }
                    conductor = ext.getIdPersonalExterno((jTable2.getValueAt(rec2, 0).toString()), "conductor");
                    tiqVarios.idConductor = conductor;
                    busTiquete.cerrar(claseTiquete);
                    dispose();
                    break;
            }
        }
    }//GEN-LAST:event_btnGuardarConductorActionPerformed

    private void btnRefrescarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarConductorActionPerformed
        busTiquete.crearModeloConductor();
    }//GEN-LAST:event_btnRefrescarConductorActionPerformed

    private void btnBuscarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConductorActionPerformed
        busTiquete.buscarConductor();
    }//GEN-LAST:event_btnBuscarConductorActionPerformed

    private void chCiudadConductorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCiudadConductorItemStateChanged
        if (chCiudadConductor.isSelected() == true) {
            txtBCiudadConductor.setEditable(true);
        } else {
            txtBCiudadConductor.setEditable(false);
            txtBCiudadConductor.setText("");
        }
    }//GEN-LAST:event_chCiudadConductorItemStateChanged

    private void chApellidosConductorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chApellidosConductorItemStateChanged
        if (chApellidosConductor.isSelected() == true) {
            txtBApellidosConductor.setEditable(true);
        } else {
            txtBApellidosConductor.setEditable(false);
            txtBApellidosConductor.setText("");
        }
    }//GEN-LAST:event_chApellidosConductorItemStateChanged

    private void chCedulaConductorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCedulaConductorItemStateChanged
        if (chCedulaConductor.isSelected() == true) {
            txtBCedulaConductor.setEditable(true);
        } else {
            txtBCedulaConductor.setEditable(false);
            txtBCedulaConductor.setText("");
        }
    }//GEN-LAST:event_chCedulaConductorItemStateChanged

    private void btnGuardarAgricultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAgricultorActionPerformed
        int rec = jTable3.getSelectedRow();
        if (rec == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
        } else {
            switch (claseTiquete) {
                case "TiqPrincipal":
                    int valor = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios realizados?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (valor == JOptionPane.YES_OPTION) {
                        Bas.txtAgricultor.setText((jTable3.getValueAt(rec, 1).toString()) + (" " + jTable3.getValueAt(rec, 2).toString()));
                    } else {
                        JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
                    }
                    String idAgricultor = ext.getIdPersonalExterno((jTable3.getValueAt(rec, 0).toString()), "agricultor");
                    bascula.idAgricultor = idAgricultor;
                    busTiquete.cerrar(claseTiquete);
                    dispose();
                    break;

                case "TiqLab":
                    String agricultor = Lab.txtAgricultor.getText();
                    if (!agricultor.equals("")) {
                        int valorl = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios realizados?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (valorl == JOptionPane.YES_OPTION) {
                            Lab.txtAgricultor.setText((jTable3.getValueAt(rec, 1).toString()) + (" " + jTable3.getValueAt(rec, 2).toString()));
                        } else {
                            JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
                        }
                    } else {
                        Lab.txtAgricultor.setText((jTable3.getValueAt(rec, 1).toString()) + (" " + jTable3.getValueAt(rec, 2).toString()));
                    }
                    agricultor = ext.getIdPersonalExterno((jTable3.getValueAt(rec, 0).toString()), "agricultor");
                    tiqLab.ccAgricultor = agricultor;
                    busTiquete.cerrar(claseTiquete);
                    dispose();
                    break;

                case "TiqLiqui":
                    Liqui.txtAgricultor.setText((jTable3.getValueAt(rec, 1).toString()) + (" " + jTable3.getValueAt(rec, 2).toString()));
                    Liqui.liqui.idAgricultor = ext.getIdPersonalExterno((jTable3.getValueAt(rec, 0).toString()), "agricultor");
                    Liqui.liqui.crearModelo();
                    dispose();
                    break;
            }
        }
    }//GEN-LAST:event_btnGuardarAgricultorActionPerformed

    /**
     * public void id_agricultor(String cedula){ try { Con = new Conexion();
     *
     * st = Con.conexion.createStatement(); rsconsecutivo =
     * st.executeQuery("SELECT idPersonalExterno FROM personalexterno where
     * cedula ='"+cedula+"'"); while (rsconsecutivo.next()) { String res =
     * rsconsecutivo.getString(1); consecutivo = (Integer.parseInt(res)+1)+""; }
     *
     * tiqLab.ccAgricultor=consecutivo;
     *
     *
     * } catch (Exception e) { e.printStackTrace(); } }
     */
    private void btnRefrescarAgricultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarAgricultorActionPerformed
        busTiquete.crearModeloAgricultor(claseTiquete);
    }//GEN-LAST:event_btnRefrescarAgricultorActionPerformed

    private void btnBuscarAgricultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAgricultorActionPerformed
        busTiquete.buscarAgricultor();
    }//GEN-LAST:event_btnBuscarAgricultorActionPerformed

    private void chCiudadAgricultorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCiudadAgricultorItemStateChanged
        if (chCiudadAgricultor.isSelected() == true) {
            txtBCiudadAgricultor.setEditable(true);
        } else {
            txtBCiudadAgricultor.setEditable(false);
            txtBCiudadAgricultor.setText("");
        }
    }//GEN-LAST:event_chCiudadAgricultorItemStateChanged

    private void chApellidosAgricultorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chApellidosAgricultorItemStateChanged
        if (chApellidosAgricultor.isSelected() == true) {
            txtBApellidosAgricultor.setEditable(true);
        } else {
            txtBApellidosAgricultor.setEditable(false);
            txtBApellidosAgricultor.setText("");
        }
    }//GEN-LAST:event_chApellidosAgricultorItemStateChanged

    private void chCedulaAgricultorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCedulaAgricultorItemStateChanged
        if (chCedulaAgricultor.isSelected() == true) {
            txtBCedulaVehiculo.setEditable(true);
        } else {
            txtBCedulaVehiculo.setEditable(false);
            txtBCedulaVehiculo.setText("");
        }
    }//GEN-LAST:event_chCedulaAgricultorItemStateChanged

    private void chPlacaVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chPlacaVehiculoItemStateChanged
        if (chPlacaVehiculo.isSelected() == true) {
            txtBPlacaVehiculo.setEditable(true);
        } else {
            txtBPlacaVehiculo.setEditable(false);
            txtBPlacaVehiculo.setText("");
        }
    }//GEN-LAST:event_chPlacaVehiculoItemStateChanged

    private void chModeloVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chModeloVehiculoItemStateChanged
        if (chModeloVehiculo.isSelected() == true) {
            txtBModeloVehiculo.setEditable(true);
        } else {
            txtBModeloVehiculo.setEditable(false);
            txtBModeloVehiculo.setText("");
        }
    }//GEN-LAST:event_chModeloVehiculoItemStateChanged

    private void chMarcaVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chMarcaVehiculoItemStateChanged
        if (chMarcaVehiculo.isSelected() == true) {
            txtBMarcaVehiculo.setEditable(true);
        } else {
            txtBMarcaVehiculo.setEditable(false);
            txtBMarcaVehiculo.setText("");
        }
    }//GEN-LAST:event_chMarcaVehiculoItemStateChanged

    private void btnBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVehiculoActionPerformed
        busTiquete.buscarVehiculo();
    }//GEN-LAST:event_btnBuscarVehiculoActionPerformed

    private void btnRefrescarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarVehiculoActionPerformed
        busTiquete.crearModeloVehiculo();
    }//GEN-LAST:event_btnRefrescarVehiculoActionPerformed

    private void btnGuardarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVehiculoActionPerformed
        int rec3 = jTable4.getSelectedRow();
        if (rec3 == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
        } else {
            switch (claseTiquete) {
                case "TiqPrincipal":
                    String placaTiqPrincipal = Bas.txtPlaca.getText();
                    if (!placaTiqPrincipal.equals("")) {
                        int valor = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios realizados?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (valor == JOptionPane.YES_OPTION) {
                            Bas.txtPlaca.setText((jTable4.getValueAt(rec3, 0).toString()));
                        } else {
                            JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
                        }
                    } else {
                        Bas.txtPlaca.setText((jTable4.getValueAt(rec3, 0).toString()));
                    }
                    busTiquete.cerrar(claseTiquete);
                    dispose();
                    break;

                case "TiqVarios":
                    String placaTiqVarios = TiqVarios.txtPlaca.getText();
                    if (!placaTiqVarios.equals("")) {
                        int valor = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios realizados?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (valor == JOptionPane.YES_OPTION) {
                            TiqVarios.txtPlaca.setText((jTable4.getValueAt(rec3, 0).toString()));
                        } else {
                            JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
                        }
                    } else {
                        TiqVarios.txtPlaca.setText((jTable4.getValueAt(rec3, 0).toString()));
                    }
                    busTiquete.cerrar(claseTiquete);
                    dispose();
                    break;
            }
        }
    }//GEN-LAST:event_btnGuardarVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedasTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedasTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedasTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedasTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BusquedasTiquete dialog = new BusquedasTiquete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnBuscarAgricultor;
    public static javax.swing.JButton btnBuscarConductor;
    public static javax.swing.JButton btnBuscarVehiculo;
    public static javax.swing.JButton btnGuardarAgricultor;
    public static javax.swing.JButton btnGuardarConductor;
    public static javax.swing.JButton btnGuardarVehiculo;
    public static javax.swing.JButton btnRefrescarAgricultor;
    public static javax.swing.JButton btnRefrescarConductor;
    public static javax.swing.JButton btnRefrescarVehiculo;
    public static javax.swing.JCheckBox chApellidosAgricultor;
    public static javax.swing.JCheckBox chApellidosConductor;
    public static javax.swing.JCheckBox chCedulaAgricultor;
    public static javax.swing.JCheckBox chCedulaConductor;
    public static javax.swing.JCheckBox chCiudadAgricultor;
    public static javax.swing.JCheckBox chCiudadConductor;
    public static javax.swing.JCheckBox chMarcaVehiculo;
    public static javax.swing.JCheckBox chModeloVehiculo;
    public static javax.swing.JCheckBox chPlacaVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JTable jTable3;
    public static javax.swing.JTable jTable4;
    public static javax.swing.JTabbedPane panel;
    public static javax.swing.JPanel panelAgricultor;
    public static javax.swing.JPanel panelConductor;
    public static javax.swing.JPanel panelVehiculo;
    public static javax.swing.JTextField txtBApellidosAgricultor;
    public static javax.swing.JTextField txtBApellidosConductor;
    public static javax.swing.JTextField txtBCedulaConductor;
    public static javax.swing.JTextField txtBCedulaVehiculo;
    public static javax.swing.JTextField txtBCiudadAgricultor;
    public static javax.swing.JTextField txtBCiudadConductor;
    public static javax.swing.JTextField txtBMarcaVehiculo;
    public static javax.swing.JTextField txtBModeloVehiculo;
    public static javax.swing.JTextField txtBPlacaVehiculo;
    // End of variables declaration//GEN-END:variables
}
