/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.Conductor.vali;
import Logica.Bascula.bascula;
import static Logica.Bascula.bascula.Bas;
import Logica.Bascula.busquedasTiquete;
import Logica.Extras.validaciones;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Andre
 */
public class BusquedasTiquete extends javax.swing.JFrame {

    public static busquedasTiquete busTiquete;
    public static bascula bascula;
    public static String claseTiquete;
    public static TiqueteVarios TiqVarios;
    public static validaciones val,vali;

    /**
     * Creates new form BusquedasTiquete
     */
    public BusquedasTiquete(String tiquete) {
        initComponents();
        setLocationRelativeTo(null);
        busTiquete = new busquedasTiquete();
        claseTiquete = tiquete;
        vali=new validaciones();
        vali.IDENTIFICACION(txtBCedulaAgricultor);
        vali.NOMBRES(txtBApellidosAgricultor);
        vali.NOMBRES(txtBCiudadAgricultor);
        vali.IDENTIFICACION(txtBCedulaConductor);
        vali.NOMBRES(txtBApellidosConductor);
        vali.NOMBRES(txtBCiudadConductor);
    }
        
    public BusquedasTiquete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel = new javax.swing.JTabbedPane();
        panelAgricultor = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        chCedulaAgricultor = new javax.swing.JCheckBox();
        chApellidosAgricultor = new javax.swing.JCheckBox();
        chCiudadAgricultor = new javax.swing.JCheckBox();
        txtBCedulaAgricultor = new javax.swing.JTextField();
        txtBApellidosAgricultor = new javax.swing.JTextField();
        txtBCiudadAgricultor = new javax.swing.JTextField();
        btnBuscarAgricultor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRefrescarAgricultor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnGuardarAgricultor = new javax.swing.JButton();
        panelConductor = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        chCedulaConductor = new javax.swing.JCheckBox();
        chApellidosConductor = new javax.swing.JCheckBox();
        chCiudadConductor = new javax.swing.JCheckBox();
        txtBCedulaConductor = new javax.swing.JTextField();
        txtBApellidosConductor = new javax.swing.JTextField();
        txtBCiudadConductor = new javax.swing.JTextField();
        btnBuscarConductor = new javax.swing.JButton();
        btnRefrescarConductor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnGuardarConductor = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelAgricultor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAgricultor.setPreferredSize(new java.awt.Dimension(1007, 367));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chCedulaAgricultor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chCedulaAgricultor.setText("Cedula");
        chCedulaAgricultor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCedulaAgricultorItemStateChanged(evt);
            }
        });

        chApellidosAgricultor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chApellidosAgricultor.setText("Apellidos");
        chApellidosAgricultor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chApellidosAgricultorItemStateChanged(evt);
            }
        });

        chCiudadAgricultor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chCiudadAgricultor.setText("Ciudad");
        chCiudadAgricultor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCiudadAgricultorItemStateChanged(evt);
            }
        });

        txtBCedulaAgricultor.setEditable(false);

        txtBApellidosAgricultor.setEditable(false);

        txtBCiudadAgricultor.setEditable(false);

        btnBuscarAgricultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        btnBuscarAgricultor.setText("Buscar");
        btnBuscarAgricultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAgricultorActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Busquedas:");

        btnRefrescarAgricultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar.png"))); // NOI18N
        btnRefrescarAgricultor.setText("Refrescar");
        btnRefrescarAgricultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarAgricultorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chCedulaAgricultor)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtBCedulaAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chApellidosAgricultor)
                            .addComponent(txtBApellidosAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBCiudadAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chCiudadAgricultor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefrescarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(316, 316, 316))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chCiudadAgricultor)
                            .addComponent(chApellidosAgricultor)
                            .addComponent(chCedulaAgricultor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBCiudadAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBApellidosAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBCedulaAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefrescarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        chCedulaAgricultor.getAccessibleContext().setAccessibleName("chCedulaAgricultor");
        chApellidosAgricultor.getAccessibleContext().setAccessibleName("chApellidosAgricultor");
        txtBCedulaAgricultor.getAccessibleContext().setAccessibleName("txtBCedulaAgricultor");
        txtBApellidosAgricultor.getAccessibleContext().setAccessibleName("txtBApellidosAgricultor");
        txtBCiudadAgricultor.getAccessibleContext().setAccessibleName("txtBCiudadAgricultor");
        btnBuscarAgricultor.getAccessibleContext().setAccessibleName("btnBuscarAgricultor");
        btnRefrescarAgricultor.getAccessibleContext().setAccessibleName("btnRefrescarAgricultor");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable3KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel2.setText("*Seleccione el agricultor en el listado y será visualizado en el tiquete de entrada.");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agricultorx64.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("AGRICULTOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        btnGuardarAgricultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        btnGuardarAgricultor.setText("Guardar");
        btnGuardarAgricultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAgricultorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgricultorLayout = new javax.swing.GroupLayout(panelAgricultor);
        panelAgricultor.setLayout(panelAgricultorLayout);
        panelAgricultorLayout.setHorizontalGroup(
            panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgricultorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgricultorLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAgricultorLayout.setVerticalGroup(
            panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgricultorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgricultorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarAgricultor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel5.getAccessibleContext().setAccessibleName("chApelliidosAgricultor");

        panel.addTab("Agricultor", panelAgricultor);
        panelAgricultor.getAccessibleContext().setAccessibleName("panelAgricultor");

        panelConductor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chCedulaConductor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chCedulaConductor.setText("Cedula");
        chCedulaConductor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCedulaConductorItemStateChanged(evt);
            }
        });

        chApellidosConductor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chApellidosConductor.setText("Apellidos");
        chApellidosConductor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chApellidosConductorItemStateChanged(evt);
            }
        });

        chCiudadConductor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chCiudadConductor.setText("Ciudad");
        chCiudadConductor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCiudadConductorItemStateChanged(evt);
            }
        });

        txtBCedulaConductor.setEditable(false);

        txtBApellidosConductor.setEditable(false);

        txtBCiudadConductor.setEditable(false);

        btnBuscarConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        btnBuscarConductor.setText("Buscar");
        btnBuscarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConductorActionPerformed(evt);
            }
        });

        btnRefrescarConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar.png"))); // NOI18N
        btnRefrescarConductor.setText("Refrescar");
        btnRefrescarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarConductorActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Busquedas:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel11)
                .addGap(316, 316, 316))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBCedulaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chCedulaConductor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chApellidosConductor)
                    .addComponent(txtBApellidosConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBCiudadConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chCiudadConductor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnRefrescarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chCedulaConductor)
                            .addComponent(chApellidosConductor)
                            .addComponent(chCiudadConductor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBCedulaConductor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBCiudadConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBApellidosConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefrescarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        chCedulaConductor.getAccessibleContext().setAccessibleName("chCedula");
        chApellidosConductor.getAccessibleContext().setAccessibleName("chApelliidos");
        chCiudadConductor.getAccessibleContext().setAccessibleName("chCiudad");
        txtBCedulaConductor.getAccessibleContext().setAccessibleName("txtBCedula");
        txtBApellidosConductor.getAccessibleContext().setAccessibleName("txtBApellidos");
        txtBCiudadConductor.getAccessibleContext().setAccessibleName("txtBCiudad");
        btnBuscarConductor.getAccessibleContext().setAccessibleName("btnBuscar");
        btnRefrescarConductor.getAccessibleContext().setAccessibleName("btnRefrescarConductor");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("*Seleccione el conductor en el listado y será visualizado en el tiquete de entrada.");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(683, 74));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/conductorx64.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CONDUCTOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        btnGuardarConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        btnGuardarConductor.setText("Guardar");
        btnGuardarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConductorLayout = new javax.swing.GroupLayout(panelConductor);
        panelConductor.setLayout(panelConductorLayout);
        panelConductorLayout.setHorizontalGroup(
            panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConductorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConductorLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConductorLayout.setVerticalGroup(
            panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConductorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConductorLayout.createSequentialGroup()
                        .addComponent(btnGuardarConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)))
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel.addTab("Conductor", panelConductor);
        panelConductor.getAccessibleContext().setAccessibleName("panelConductor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 747, 556);
    }// </editor-fold>//GEN-END:initComponents
    /**
     *
     * AGRICULTOR
     */
    private void chCedulaAgricultorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCedulaAgricultorItemStateChanged
        if (chCedulaAgricultor.isSelected() == true) {
            txtBCedulaAgricultor.setEditable(true);
        } else {
            txtBCedulaAgricultor.setEditable(false);
            txtBCedulaAgricultor.setText("");
        }
    }//GEN-LAST:event_chCedulaAgricultorItemStateChanged

    private void btnBuscarAgricultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAgricultorActionPerformed
        busTiquete.buscarAgricultor();

    }//GEN-LAST:event_btnBuscarAgricultorActionPerformed

    private void chApellidosAgricultorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chApellidosAgricultorItemStateChanged
        if (chApellidosAgricultor.isSelected() == true) {
            txtBApellidosAgricultor.setEditable(true);
        } else {
            txtBApellidosAgricultor.setEditable(false);
            txtBApellidosAgricultor.setText("");
        }
    }//GEN-LAST:event_chApellidosAgricultorItemStateChanged

    private void chCiudadAgricultorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCiudadAgricultorItemStateChanged
        if (chCiudadAgricultor.isSelected() == true) {
            txtBCiudadAgricultor.setEditable(true);
        } else {
            txtBCiudadAgricultor.setEditable(false);
            txtBCiudadAgricultor.setText("");
        }
    }//GEN-LAST:event_chCiudadAgricultorItemStateChanged

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        //busTiquete.tabla_camposAgricultor();
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyReleased
        //busTiquete.tabla_camposAgricultor();
    }//GEN-LAST:event_jTable3KeyReleased

    /**
     *
     * CONDUCTOR
     */
    private void chCedulaConductorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCedulaConductorItemStateChanged
        if (chCedulaConductor.isSelected() == true) {
            txtBCedulaConductor.setEditable(true);
        } else {
            txtBCedulaConductor.setEditable(false);
            txtBCedulaConductor.setText("");
        }
    }//GEN-LAST:event_chCedulaConductorItemStateChanged

    private void chApellidosConductorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chApellidosConductorItemStateChanged
        if (chApellidosConductor.isSelected() == true) {
            txtBApellidosConductor.setEditable(true);
        } else {
            txtBApellidosConductor.setEditable(false);
            txtBApellidosConductor.setText("");
        }
    }//GEN-LAST:event_chApellidosConductorItemStateChanged

    private void chCiudadConductorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCiudadConductorItemStateChanged
        if (chCiudadConductor.isSelected() == true) {
            txtBCiudadConductor.setEditable(true);
        } else {
            txtBCiudadConductor.setEditable(false);
            txtBCiudadConductor.setText("");
        }
    }//GEN-LAST:event_chCiudadConductorItemStateChanged

    private void btnBuscarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConductorActionPerformed
        busTiquete.buscarConductor();
    }//GEN-LAST:event_btnBuscarConductorActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        //busTiquete.tabla_camposConductor();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        //busTiquete.tabla_camposConductor();
    }//GEN-LAST:event_jTable2KeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        busTiquete.cerrar(claseTiquete);
        busTiquete.desactivar_checkboxConductor();
        busTiquete.desactivar_checkboxAgricultor();
    }//GEN-LAST:event_formWindowClosing

    private void btnRefrescarAgricultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarAgricultorActionPerformed
        busTiquete.crearModeloAgricultor();
    }//GEN-LAST:event_btnRefrescarAgricultorActionPerformed

    private void btnRefrescarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarConductorActionPerformed
        busTiquete.crearModeloConductor();
    }//GEN-LAST:event_btnRefrescarConductorActionPerformed

    private void btnGuardarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConductorActionPerformed

        int rec2 = jTable2.getSelectedRow();
        if (rec2 == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
        } else {
            int valor = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios realizados?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (valor == JOptionPane.YES_OPTION) {

                switch (claseTiquete) {

                    case "TiqPrincipal":
                        Bas.txtConductor.setText((jTable2.getValueAt(rec2, 1).toString()) + (" " + jTable2.getValueAt(rec2, 2).toString()));
                        busTiquete.cerrar(claseTiquete);
                        dispose();
                        break;

                    case "TiqVarios":
                        TiqVarios.txtConductor.setText((jTable2.getValueAt(rec2, 1).toString()) + (" " + jTable2.getValueAt(rec2, 2).toString()));
                        busTiquete.cerrar(claseTiquete);
                        dispose();
                        break;
                }

            } else {
                JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
            }
        }

    }//GEN-LAST:event_btnGuardarConductorActionPerformed

    private void btnGuardarAgricultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAgricultorActionPerformed
        int rec = jTable3.getSelectedRow();
        if (rec == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
        } else {
            int valor = JOptionPane.showConfirmDialog(null, "Desea guardar los cambios realizados?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (valor == JOptionPane.YES_OPTION) {

                switch (claseTiquete) {
                    case "TiqPrincipal":
                        Bas.txtAgricultor.setText((jTable3.getValueAt(rec, 1).toString()) + (" " + jTable3.getValueAt(rec, 2).toString()));
                        busTiquete.cerrar(claseTiquete);
                        dispose();
                        break;    
                }

            } else {
                JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
            }
        }
    }//GEN-LAST:event_btnGuardarAgricultorActionPerformed

    public void btnGuardarAgricultor(String claseTiquete) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedasTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedasTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedasTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedasTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedasTiquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnBuscarAgricultor;
    public static javax.swing.JButton btnBuscarConductor;
    public static javax.swing.JButton btnGuardarAgricultor;
    public static javax.swing.JButton btnGuardarConductor;
    public static javax.swing.JButton btnRefrescarAgricultor;
    public static javax.swing.JButton btnRefrescarConductor;
    public static javax.swing.JCheckBox chApellidosAgricultor;
    public static javax.swing.JCheckBox chApellidosConductor;
    public static javax.swing.JCheckBox chCedulaAgricultor;
    public static javax.swing.JCheckBox chCedulaConductor;
    public static javax.swing.JCheckBox chCiudadAgricultor;
    public static javax.swing.JCheckBox chCiudadConductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JTable jTable3;
    public static javax.swing.JTabbedPane panel;
    public static javax.swing.JPanel panelAgricultor;
    public static javax.swing.JPanel panelConductor;
    public static javax.swing.JTextField txtBApellidosAgricultor;
    public static javax.swing.JTextField txtBApellidosConductor;
    public static javax.swing.JTextField txtBCedulaAgricultor;
    public static javax.swing.JTextField txtBCedulaConductor;
    public static javax.swing.JTextField txtBCiudadAgricultor;
    public static javax.swing.JTextField txtBCiudadConductor;
    // End of variables declaration//GEN-END:variables
}
