/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Logica.Extras.validaciones;
import javax.swing.JOptionPane;
import Logica.Liquidacion.liquidacion;

/**
 *
 * @author jhonansmith
 */
public class Liquidacion extends javax.swing.JFrame {

    public static liquidacion liqui;
    public static validaciones vali;

    /**
     * Creates new form Liquidacion
     */
    public Liquidacion() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        liqui = new liquidacion();
        vali = new validaciones();
        vali.DECIMAL(txtHumedadIdeal);
        vali.DECIMAL(txtImpurezaIdeal);
        vali.DECIMAL(txtFomArroz);
        vali.DECIMAL(txtImpuesto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHumedadIdeal = new javax.swing.JLabel();
        lblImpuerzaIdeal = new javax.swing.JLabel();
        lblFomArroz = new javax.swing.JLabel();
        lblTipoImpuesto = new javax.swing.JLabel();
        lblImpuesto = new javax.swing.JLabel();
        txtHumedadIdeal = new javax.swing.JTextField();
        txtImpurezaIdeal = new javax.swing.JTextField();
        txtFomArroz = new javax.swing.JTextField();
        txtImpuesto = new javax.swing.JTextField();
        cmbImpuesto = new javax.swing.JComboBox<>();
        lblDesAnticipo = new javax.swing.JLabel();
        txtDesAnticipo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeleccionTiquete = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSeleccionLiquidacion = new javax.swing.JTable();
        btnPasarTodo = new javax.swing.JButton();
        btnPasarUno = new javax.swing.JButton();
        btnDevolverTodo = new javax.swing.JButton();
        btnDevolverUno = new javax.swing.JButton();
        txtAgricultor = new javax.swing.JTextField();
        btnBuscarAgricultor = new javax.swing.JButton();
        lblAnuncio = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTotalKilosNetos = new javax.swing.JLabel();
        lblTotalKilosCompra = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblImpuestoLiqui = new javax.swing.JLabel();
        lblFomArrozLiqui = new javax.swing.JLabel();
        lblNetoPagar = new javax.swing.JLabel();
        txtTotalKilosNeto = new javax.swing.JTextField();
        txtTotalKilosCompra = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        txtFomArroceroLiqui = new javax.swing.JTextField();
        txtImpuestoLiqui = new javax.swing.JTextField();
        txtNetoPagar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnGenerar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblHumedadIdeal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHumedadIdeal.setText("Humedad Ideal:");

        lblImpuerzaIdeal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblImpuerzaIdeal.setText("Impuerza Ideal:");

        lblFomArroz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFomArroz.setText("% Fomento Arrocero:");

        lblTipoImpuesto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipoImpuesto.setText("Tipo De Impuesto:");

        lblImpuesto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblImpuesto.setText("% Impuesto:");

        txtHumedadIdeal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHumedadIdealFocusLost(evt);
            }
        });

        txtImpurezaIdeal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtImpurezaIdealFocusLost(evt);
            }
        });

        txtFomArroz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFomArrozFocusLost(evt);
            }
        });

        txtImpuesto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtImpuestoFocusLost(evt);
            }
        });

        cmbImpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retefuente", "Comisión Bolsa" }));
        cmbImpuesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbImpuestoItemStateChanged(evt);
            }
        });

        lblDesAnticipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDesAnticipo.setText("Descuento Anticipo:");

        txtDesAnticipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDesAnticipoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDesAnticipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDesAnticipo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImpuesto)
                        .addGap(54, 54, 54)
                        .addComponent(txtImpuesto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFomArroz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFomArroz))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHumedadIdeal)
                            .addComponent(lblImpuerzaIdeal))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImpurezaIdeal)
                            .addComponent(txtHumedadIdeal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipoImpuesto)
                        .addGap(18, 18, 18)
                        .addComponent(cmbImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHumedadIdeal)
                    .addComponent(txtHumedadIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuerzaIdeal)
                    .addComponent(txtImpurezaIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFomArroz)
                    .addComponent(txtFomArroz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoImpuesto)
                    .addComponent(cmbImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuesto)
                    .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesAnticipo)
                    .addComponent(txtDesAnticipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("Crear Liquidación");

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/liquidacion.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblSeleccionTiquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Fecha", "Agricultor", "Valor Carga", "Kilos Netos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSeleccionTiquete);
        if (tblSeleccionTiquete.getColumnModel().getColumnCount() > 0) {
            tblSeleccionTiquete.getColumnModel().getColumn(0).setMinWidth(30);
            tblSeleccionTiquete.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        tblSeleccionLiquidacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Kilos Brutos", "Humedad", "Impureza", "Castigo Humedad", "Castigo Impureza", "Peso Compra", "Valor Kilo", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSeleccionLiquidacion);

        btnPasarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/double-right.png"))); // NOI18N
        btnPasarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarTodoActionPerformed(evt);
            }
        });

        btnPasarUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/only-right.png"))); // NOI18N
        btnPasarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarUnoActionPerformed(evt);
            }
        });

        btnDevolverTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/double-left.png"))); // NOI18N
        btnDevolverTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverTodoActionPerformed(evt);
            }
        });

        btnDevolverUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/only-left.png"))); // NOI18N
        btnDevolverUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverUnoActionPerformed(evt);
            }
        });

        txtAgricultor.setEditable(false);

        btnBuscarAgricultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        btnBuscarAgricultor.setText("Buscar");
        btnBuscarAgricultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAgricultorActionPerformed(evt);
            }
        });

        lblAnuncio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAnuncio.setText("Por favor buscar un agricultor para crear una liquidación");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPasarTodo)
                    .addComponent(btnPasarUno)
                    .addComponent(btnDevolverTodo)
                    .addComponent(btnDevolverUno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnBuscarAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAnuncio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblAnuncio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgricultor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAgricultor))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnPasarTodo)
                        .addGap(27, 27, 27)
                        .addComponent(btnPasarUno)
                        .addGap(18, 18, 18)
                        .addComponent(btnDevolverTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDevolverUno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addGap(16, 16, 16))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTotalKilosNetos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalKilosNetos.setText("Total Kilos Netos:");

        lblTotalKilosCompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalKilosCompra.setText("Total Kilos Compra:");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSubTotal.setText("SubTotal:");

        lblImpuestoLiqui.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblImpuestoLiqui.setText("Retefuente:");

        lblFomArrozLiqui.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFomArrozLiqui.setText("Fomento Arrocero:");

        lblNetoPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNetoPagar.setText("Neto A Pagar:");

        txtTotalKilosNeto.setEditable(false);

        txtTotalKilosCompra.setEditable(false);

        txtSubTotal.setEditable(false);

        txtFomArroceroLiqui.setEditable(false);

        txtImpuestoLiqui.setEditable(false);

        txtNetoPagar.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalKilosNetos)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTotalKilosCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSubTotal))
                    .addComponent(lblImpuestoLiqui)
                    .addComponent(lblNetoPagar)
                    .addComponent(lblFomArrozLiqui))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalKilosNeto)
                    .addComponent(txtTotalKilosCompra)
                    .addComponent(txtSubTotal)
                    .addComponent(txtFomArroceroLiqui)
                    .addComponent(txtImpuestoLiqui)
                    .addComponent(txtNetoPagar))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalKilosNetos)
                    .addComponent(txtTotalKilosNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalKilosCompra)
                    .addComponent(txtTotalKilosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFomArrozLiqui)
                    .addComponent(txtFomArroceroLiqui, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuestoLiqui)
                    .addComponent(txtImpuestoLiqui, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNetoPagar)
                    .addComponent(txtNetoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jMenu1.setText("Liquidaciones");

        jMenuItem2.setText("Crear");
        jMenu1.add(jMenuItem2);

        mnGenerar.setText("Generar");
        mnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGenerarActionPerformed(evt);
            }
        });
        jMenu1.add(mnGenerar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cuenta");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasarUnoActionPerformed
        liqui.moverTabla("unoDerecha");
    }//GEN-LAST:event_btnPasarUnoActionPerformed

    private void btnBuscarAgricultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAgricultorActionPerformed
        // TODO add your handling code here:
        String texto = txtAgricultor.getText();
        if (!texto.equals("")) {
            int valor = JOptionPane.showConfirmDialog(null, "Desea realmente editar el nombre del Agricultor?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (valor == JOptionPane.YES_OPTION) {
                liqui.abrirBusquedasTiquete("TiqLiqui");
            } else {
                JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");
            }
        } else {
            liqui.abrirBusquedasTiquete("TiqLiqui");
        }
    }//GEN-LAST:event_btnBuscarAgricultorActionPerformed

    private void btnPasarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasarTodoActionPerformed
        liqui.moverTabla("todoDerecha");
    }//GEN-LAST:event_btnPasarTodoActionPerformed

    private void btnDevolverTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverTodoActionPerformed
        liqui.moverTabla("todoIzquierda");
    }//GEN-LAST:event_btnDevolverTodoActionPerformed

    private void btnDevolverUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverUnoActionPerformed
        liqui.moverTabla("unoIzquierda");
    }//GEN-LAST:event_btnDevolverUnoActionPerformed

    private void txtHumedadIdealFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHumedadIdealFocusLost
        liqui.completarTablaLiquidacion();
    }//GEN-LAST:event_txtHumedadIdealFocusLost

    private void txtImpurezaIdealFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImpurezaIdealFocusLost
        liqui.completarTablaLiquidacion();
    }//GEN-LAST:event_txtImpurezaIdealFocusLost

    private void txtFomArrozFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFomArrozFocusLost
        liqui.completarTablaLiquidacion();
    }//GEN-LAST:event_txtFomArrozFocusLost

    private void txtImpuestoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImpuestoFocusLost
        liqui.completarTablaLiquidacion();
    }//GEN-LAST:event_txtImpuestoFocusLost

    private void txtDesAnticipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDesAnticipoFocusLost
        liqui.completarTablaLiquidacion();
    }//GEN-LAST:event_txtDesAnticipoFocusLost

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        liqui.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cmbImpuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbImpuestoItemStateChanged
        liqui.getImpuesto();
    }//GEN-LAST:event_cmbImpuestoItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        liqui.crearLiquidacion();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        liqui.salir();
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGenerarActionPerformed
        liqui.mnGenerarLiquiacion();
    }//GEN-LAST:event_mnGenerarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liquidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnBuscarAgricultor;
    public static javax.swing.JButton btnDevolverTodo;
    public static javax.swing.JButton btnDevolverUno;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnLimpiar;
    public static javax.swing.JButton btnPasarTodo;
    public static javax.swing.JButton btnPasarUno;
    public static javax.swing.JComboBox<String> cmbImpuesto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnuncio;
    private javax.swing.JLabel lblDesAnticipo;
    private javax.swing.JLabel lblFomArroz;
    private javax.swing.JLabel lblFomArrozLiqui;
    private javax.swing.JLabel lblHumedadIdeal;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImpuerzaIdeal;
    private javax.swing.JLabel lblImpuesto;
    public static javax.swing.JLabel lblImpuestoLiqui;
    private javax.swing.JLabel lblNetoPagar;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTipoImpuesto;
    private javax.swing.JLabel lblTotalKilosCompra;
    private javax.swing.JLabel lblTotalKilosNetos;
    public javax.swing.JMenuItem mnGenerar;
    public static javax.swing.JTable tblSeleccionLiquidacion;
    public static javax.swing.JTable tblSeleccionTiquete;
    public static javax.swing.JTextField txtAgricultor;
    public static javax.swing.JTextField txtDesAnticipo;
    public static javax.swing.JTextField txtFomArroceroLiqui;
    public static javax.swing.JTextField txtFomArroz;
    public static javax.swing.JTextField txtHumedadIdeal;
    public static javax.swing.JTextField txtImpuesto;
    public static javax.swing.JTextField txtImpuestoLiqui;
    public static javax.swing.JTextField txtImpurezaIdeal;
    public static javax.swing.JTextField txtNetoPagar;
    public static javax.swing.JTextField txtSubTotal;
    public static javax.swing.JTextField txtTotalKilosCompra;
    public static javax.swing.JTextField txtTotalKilosNeto;
    // End of variables declaration//GEN-END:variables
}
